services:
  postgres:
    image: 'postgres:latest'
    restart: always
    environment:
      POSTGRES_DB: pdb
      POSTGRES_PASSWORD: bee
      POSTGRES_USER: bee
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/create.sql
volumes:
  db-data: