server:
  address: 127.0.0.1
  port: 8088
logging:
  level:
    root: "info"
    org.springframework.web: "debug"
  file:
    name: logging.log
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/pdb
    username: bee
    password: bee
    # Connection pool properties
    hikari:
      connectionTimeout: 20000
      maximumPoolSize: 5
  sql:
    init:
      platform: postgres
      schema-locations:
        - classpath:/db/migration/V00001__create_table_product.sql
        - classpath:/db/migration/V00001__create_table_customer.sql
      data-locations:
        - classpath:/db/migration/V00002__insert_customer.sql
        - classpath:/db/migration/V00002__insert_products.sql
      mode: always
  flyway:
    enabled: false
  activemq:
    broker-url: tcp://localhost:61616
    activemq:
      user: admin
      password: admin
  jpa:
    hibernate:
      ddl-auto:  none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
      javax:
        persistence:
          schema-generation:
            scripts:
              action: none
              create-target: create.sql
    datasource:

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 50MB